force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>This object refers to the Appointment logs</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Doctor__c/Appointment_Doctor__c.object-meta.xml
<CustomObject>
    <label>Appointment/Doctor</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Appointment Doctor #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment/Doctors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Doctor__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointment_Doctors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_Doctor__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipName>Appointment_Doctors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>This object refers to the Doctor</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentDoctorTriggerTest.cls
@isTest
private with sharing class AppointmentDoctorTriggerTest {
@TestSetup
static void makeDataAD(){
TestDataFactory.appointmentTestData(200);
TestDataFactory.doctorTestData(200);
}
@isTest
private static void junctionOnj() {

List<Appointment__c> listApp = [SELECT id FROM Appointment__c];
List<Doctor__c> listDoc = [SELECT id FROM Doctor__c];

List<Appointment_Doctor__c> adFullList =new List<Appointment_Doctor__c>();
for (Integer i = 0; i < listApp.size(); i++) {
    Appointment_Doctor__c ad =new Appointment_Doctor__c();
    ad.Appointment__c = listApp[i].id;
    ad.Doctor__c = listDoc[i].id;
    adFullList.add(ad);       
}
system.debug(adFullList.size());
system.debug(adFullList);
insert adFullList;

test.startTest();
AppointmentDoctorTriggerHandler.duplicateDoctorAppError(adFullList);
test.stopTest();

Assert.isTrue(!adFullList.isEmpty());
Assert.areEqual(200, adFullList.size());
}
}