force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>This object refers to the Appointment logs</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Type__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Type__c</fullName>
    <label>Appointment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Clinic_Manager__c.field-meta.xml
<CustomField>
    <fullName>Clinic_Manager__c</fullName>
    <label>Clinic Manager</label>
    <referenceTo>Clinic_Manager__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Pediatric</fullName>
            </value>
            <value>
                <fullName>Physiotherapy and Rehabilitation</fullName>
            </value>
            <value>
                <fullName>Public Health</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Maximum_number_of_patients__c.field-meta.xml
<CustomField>
    <fullName>Maximum_number_of_patients__c</fullName>
    <label>Maximum number of patients</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patients_Attending__c.field-meta.xml
<CustomField>
    <fullName>Patients_Attending__c</fullName>
    <label># Patients Attending</label>
    <summaryForeignKey>Appointment_Patient__c.Appointment__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Remaining_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Appointment__c</fullName>
    <formula>Maximum_number_of_patients__c  -  Patients_Attending__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Appointment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinic_Manager__c/Clinic_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is to organize the clinic</description>
    <label>Clinic Manager</label>
    <nameField>
        <label>Clinic Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic Managers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinic_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Clinic Managers</relationshipLabel>
    <relationshipName>Clinic_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>This object refers to Clinic Locations</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentWebService.cls
@RestResource (urlMapping='/Appointment/*')
global with sharing class AppointmentWebService {
    @HttpGet
    global static List<appWrapper> appointmentWebServiceGet() {
        List<appWrapper> details = new List<appWrapper>();
        for(Appointment__c evt: [SELECT Id, Appointment_Type__c, Clinic_Manager__r.Name, Department__c, End_Date_Time__c, Frequency__c, Live__c, Location_Verified__c, Location__r.Name, Maximum_number_of_patients__c, Name__c, Patients_Attending__c, Recurring__c, Remaining_Appointment__c, Start_Date_Time__c, Status__c FROM Appointment__c WITH SECURITY_ENFORCED]){
            details.add(new appWrapper(evt));
        }
        return details;
    }
    global class AppWrapper {
        Public String id;
        Public String appointmentType;
        Public String clinicManagerName;
        Public String department;
        Public String frequency;
        Public String locationName;
        Public String name;
        Public String status;
        Public Decimal patientsAttending;
        Public Decimal remainingAppointment;
        Public Decimal maximumNumberOfPatients;
        Public Boolean recurring;
        Public Boolean live;
        Public Boolean locationVerified;
        Public String endDateTime;
        Public String startDateTime;
    public appWrapper(Appointment__c evt) {
        this.Id = evt.Id;
        this.appointmentType = evt.Appointment_Type__c;
        this.clinicManagerName = evt.Clinic_Manager__r.Name;
        this.Department = evt.Department__c;
        this.Frequency = evt.Frequency__c;
        this.locationName = evt.Location__r.Name;
        this.Name = evt.Name__c;
        this.Status = evt.Status__c;
        this.patientsAttending = evt.Patients_Attending__c;
        this.remainingAppointment = evt.Remaining_Appointment__c;
        this.maximumNumberOfPatients = evt.Maximum_number_of_patients__c;
        this.Recurring = evt.Recurring__c;
        this.Live = evt.Live__c;
        this.locationVerified = evt.Location_Verified__c;
        this.endDateTime = evt.End_Date_Time__c?.format('yyyy-mm-dd hh:mm');
        this.startDateTime = evt.Start_Date_Time__c?.format('yyyy-mm-dd hh:mm');
    }
    }
}