force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>This object refers to the Doctor</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Doctor_License__c.field-meta.xml
<CustomField>
    <fullName>Doctor_License__c</fullName>
    <label>Doctor License</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/DoctorTriggerHandler.cls
public class DoctorTriggerHandler {
    public static void updateDoctorLicense(list<doctor__c> triggerNew) {
        try {
            for (Doctor__c newdoc : triggernew) {
                Boolean b = newdoc.Doctor_License__c.contains('ABC123456789'); 
                }
            }catch (Exception e) {
            ErrorLog.createErrorLog(date.today(), e.getMessage(), 'createDoctor'); 
        }
    }
}